### ISSUE TITLE
User Story: Retrieve Similar Posts

### ISSUE THREAD

**Issue by OJarvey** [OJarvey/blog.project4#14]
EPIC: <epic>
As a blog user, I want to see a list of posts similar to the one I am reading, so that I can easily discover related content.

### Acceptance Criteria

- [x] A list of up to 5 similar posts is displayed on the post detail page.
- [x] Similarity is determined by shared tags.
- [x] Each post in the list links to its detail page.

### Tasks

1. Add functionality in the Post model to find similar posts using shared tags.
2. Update the post_detail view to include similar posts in the context.
3. Modify the post_detail.html template to display the similar posts section.
